enableFeaturePreview("VERSION_CATALOGS")
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include(":app")
include(":core-ui")
include(":core-network")
include(":core-testing")
include(":core-utils")
include(":core-extension")
include(":core-resource")
include(":core-data")
include(":feature-weather:feature-weather-ui")
include(":feature-weather:feature-weather-kit")
include(":feature-login:feature-login-ui")
include(":feature-login:feature-login-kit")
